# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heimdallr_grpc/heimdallr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eheimdallr_grpc/heimdallr.proto\x12\x0eheimdallr_grpc\",\n\x0bGoToRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\"?\n\x0cResponseCode\x12/\n\x08Response\x18\x01 \x01(\x0e\x32\x1d.heimdallr_grpc.ResponseCodes*8\n\rResponseCodes\x12\x10\n\x0cResp_Success\x10\x00\x12\x15\n\x11Resp_GenericError\x10\x01\x32\xe4\x01\n\x06idaRPC\x12G\n\ndisasmGoTo\x12\x1b.heimdallr_grpc.GoToRequest\x1a\x1c.heimdallr_grpc.ResponseCode\x12G\n\npseudoGoTo\x12\x1b.heimdallr_grpc.GoToRequest\x1a\x1c.heimdallr_grpc.ResponseCode\x12H\n\x0bgenericGoTo\x12\x1b.heimdallr_grpc.GoToRequest\x1a\x1c.heimdallr_grpc.ResponseCodeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heimdallr_grpc.heimdallr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSECODES._serialized_start=161
  _RESPONSECODES._serialized_end=217
  _GOTOREQUEST._serialized_start=50
  _GOTOREQUEST._serialized_end=94
  _RESPONSECODE._serialized_start=96
  _RESPONSECODE._serialized_end=159
  _IDARPC._serialized_start=220
  _IDARPC._serialized_end=448
# @@protoc_insertion_point(module_scope)
